# Generated by Django 3.2 on 2024-02-06 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20240206_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(50, 'Review must be greater than 50 characters')]),
        ),
    ]
